import { atom } from "jotai";

import errandsData from "../errands";

// User active lists
let userLists = [
  {
    id: "900f87",
    ownerId: "100001",
    title: "Personal",
    icon: "person",
    color: "blue",
  },
  {
    id: "12439l",
    ownerId: "100001",
    title: "Supermercado",
    icon: "restaurant",
    color: "yellow",
  },
  {
    id: "9dsmnb",
    ownerId: "100001",
    title: "Trabajo",
    icon: "business",
    color: "orange",
  },
  {
    id: "9dwe32",
    ownerId: "100001",
    title: "Universidad",
    icon: "book",
    color: "green",
  },
];

// User active
let userExample = {
  id: "100001",
  username: "manelmb9",
  name: "Manel",
  surname: "Martinez Bel",
  email: "manel.mb@example.com",
  phoneNumber: "+34-600-123-456",
  settings: {
    notifications: {
      email: true,
      sms: false,
      push: true,
    },
    language: "es",
    privacy: {
      profileVisibility: "friends",
      lastSeen: "contacts",
    },
  },
  photoURL: false,
  contacts: [
    {
      id: "100002",
      name: "Carlos",
      surname: "Fernández",
      phoneNumber: "+34678901234",
      email: "carlos.fernandez@email.com",
      favorite: true,
      blocked: false,
      muted: {
        muteAll: false,
        muteMessages: false,
        muteNewErrands: false,
        muteReminders: false,
        muteChangesInErrands: false,
      },
    },
    {
      id: "100003",
      name: "María",
      surname: "Gómez",
      phoneNumber: "+34612345678",
      favorite: false,
      blocked: false,
      muted: {
        muteAll: false,
        muteMessages: false,
        muteNewErrands: false,
        muteReminders: false,
        muteChangesInErrands: false,
      },
    },
    {
      id: "100004",
      name: "Alejandro",
      surname: "Ruiz",
      phoneNumber: "+34655544332",
      email: "alejandro.ruiz@email.com",
      favorite: true,
      blocked: false,
      muted: {
        muteAll: false,
        muteMessages: true,
        muteNewErrands: false,
        muteReminders: false,
        muteChangesInErrands: false,
      },
    },
    {
      id: "100005",
      name: "Lucía",
      surname: "Martínez",
      phoneNumber: "+34699988877",
      favorite: false,
      blocked: false,
      muted: {
        muteAll: true,
        muteMessages: true,
        muteNewErrands: true,
        muteReminders: true,
        muteChangesInErrands: true,
      },
    },
    {
      id: "100006",
      name: "Javier",
      surname: "López",
      phoneNumber: "+34677766655",
      email: "javier.lopez@email.com",
      favorite: true,
      blocked: false,
      muted: {
        muteAll: true,
        muteMessages: true,
        muteNewErrands: true,
        muteReminders: true,
        muteChangesInErrands: true,
      },
    },
    {
      id: "100007",
      name: "Sofía",
      surname: "Hernández",
      phoneNumber: "+34623456789",
      favorite: false,
      blocked: false,
      muted: {
        muteAll: true,
        muteMessages: true,
        muteNewErrands: true,
        muteReminders: true,
        muteChangesInErrands: true,
      },
    },
    {
      id: "100008",
      name: "Daniel",
      surname: "Pérez",
      phoneNumber: "+34687654321",
      email: "daniel.perez@email.com",
      favorite: true,
      blocked: false,
      muted: {
        muteAll: false,
        muteMessages: false,
        muteNewErrands: true,
        muteReminders: false,
        muteChangesInErrands: true,
      },
    },
    {
      id: "100009",
      name: "Elena",
      surname: "Díaz",
      phoneNumber: "+34611223344",
      favorite: false,
      blocked: false,
      muted: {
        muteAll: false,
        muteMessages: false,
        muteNewErrands: false,
        muteReminders: false,
        muteChangesInErrands: true,
      },
    },
    {
      id: "100010",
      name: "Pedro",
      surname: "Torres",
      phoneNumber: "+34655667788",
      email: "pedro.torres@email.com",
      favorite: false,
      blocked: false,
      muted: {
        muteAll: false,
        muteMessages: false,
        muteNewErrands: true,
        muteReminders: false,
        muteChangesInErrands: false,
      },
    },
    {
      id: "100011",
      name: "Natalia",
      surname: "Romero",
      phoneNumber: "+34699887766",
      favorite: false,
      blocked: false,
      muted: {
        muteAll: false,
        muteMessages: false,
        muteNewErrands: true,
        muteReminders: true,
        muteChangesInErrands: true,
      },
    },
    {
      id: "100012",
      name: "Hugo",
      surname: "Sánchez",
      phoneNumber: "+34622334455",
      email: "hugo.sanchez@email.com",
      favorite: true,
      blocked: false,
      muted: {
        muteAll: false,
        muteMessages: true,
        muteNewErrands: true,
        muteReminders: false,
        muteChangesInErrands: true,
      },
    },
    {
      id: "100013",
      name: "Andrea",
      surname: "Vargas",
      phoneNumber: "+34633445566",
      favorite: false,
      blocked: false,
      muted: {
        muteAll: false,
        muteMessages: true,
        muteNewErrands: true,
        muteReminders: false,
        muteChangesInErrands: true,
      },
    },
    {
      id: "100014",
      name: "Miguel",
      surname: "Navarro",
      phoneNumber: "+34644556677",
      email: "miguel.navarro@email.com",
      favorite: true,
      blocked: false,
      muted: {
        muteAll: false,
        muteMessages: true,
        muteNewErrands: false,
        muteReminders: true,
        muteChangesInErrands: true,
      },
    },
    {
      id: "1000015",
      name: "Laura",
      surname: "Ortega",
      phoneNumber: "+34655667799",
      favorite: false,
      blocked: false,
      muted: {
        muteAll: false,
        muteMessages: true,
        muteNewErrands: true,
        muteReminders: false,
        muteChangesInErrands: false,
      },
    },
    {
      id: "100016",
      name: "Fernando",
      surname: "Castro",
      phoneNumber: "+34666778899",
      email: "fernando.castro@email.com",
      favorite: true,
      blocked: false,
      muted: {
        muteAll: false,
        muteMessages: false,
        muteNewErrands: false,
        muteReminders: true,
        muteChangesInErrands: true,
      },
    },
  ],
  createdAt: "2023-10-01T12:00:00.000Z",
  updatedAt: "2023-10-01T12:00:00.000Z",
};

export const userAtom = atom(userExample);
export const errandsAtom = atom(errandsData);
export const listsAtom = atom(userLists);
export const currentErrandAtom = atom(null);
export const userAssignedAtom = atom(userExample);
export const listAssignedAtom = atom(false);
export const contactsAtom = atom(userExample.contacts);
export const themeAtom = atom("light");
export const languageAtom = atom("es");
