export const themes = {
  light: {
    background: "#F5F5F5",
    blueHeadText: "#007AFF",
    text: "#1E1E1E",
    buttonMenuBackground: "#FFFFFF",
    sendTaskButtonText: "#3F3F3F",
    taskTitle: "#1E1E1E",
    taskSecondText: "#6E727A",
    addNewTaskText: "#A2A6AD",
    submittedTaskToBg: "#CDE7E2",
    taskReceivedFromBg: "#CDC9FB",
    listTitle: "#161618",
    listsSeparator: "#6b7280",
  },
  dark: {
    background: "#121212",
    blueHeadText: "#007AFF",
    text: "#FDFDFD",
    buttonMenuBackground: "#1f2120",
    sendTaskButtonText: "#7A7A7A",
    taskTitle: "#FDFDFD",
    taskSecondText: "#6E727A",
    addNewTaskText: "#4B4F55",
    submittedTaskToBg: "#CDE7E2",
    taskReceivedFromBg: "#CDC9FB",
    listTitle: "#BFBFBF",
    listsSeparator: "#6b7280",
  },
};
