const today = new Date().toISOString().split("T")[0];
const yesterday = new Date(new Date().setDate(new Date().getDate() - 1))
  .toISOString()
  .split("T")[0];
const twoDaysAgo = new Date(new Date().setDate(new Date().getDate() - 2))
  .toISOString()
  .split("T")[0];
const threeDaysAgo = new Date(new Date().setDate(new Date().getDate() - 3))
  .toISOString()
  .split("T")[0];
const tomorrow = new Date(new Date().setDate(new Date().getDate() + 1))
  .toISOString()
  .split("T")[0];
const twoDaysLater = new Date(new Date().setDate(new Date().getDate() + 2))
  .toISOString()
  .split("T")[0];
const threeDaysLater = new Date(new Date().setDate(new Date().getDate() + 3))
  .toISOString()
  .split("T")[0];
const fourDaysLater = new Date(new Date().setDate(new Date().getDate() + 4))
  .toISOString()
  .split("T")[0];

const errandsData = [
  {
    id: "122648720482",
    ownerId: "100002",
    assignedId: "100001",
    title: "Pick up documents",
    description: "Pick up lawyer documents from the office.",
    dateErrand: today,
    timeErrand: "20:00",
    completed: false,
    dateNotice: today,
    timeNotice: "18:00",
    repeat: "never",
    marked: true,
    location: "Main Street, Dry Cleaners",
    priority: "medium",
    listId: "",
    subtasks: {},
    completedDateErrand: "",
    completedTimeErrand: "",
    seen: true,
    deleted: false,
  },
  {
    id: "123321789987",
    ownerId: "100001",
    assignedId: "100002",
    title: "Pick up dry cleaning",
    description: "Pick up the dry cleaning from the shop on Main Street.",
    dateErrand: yesterday,
    timeErrand: "10:00",
    completed: true,
    dateNotice: yesterday,
    timeNotice: "09:00",
    repeat: "never",
    marked: true,
    location: "Main Street, Dry Cleaners",
    priority: "medium",
    listId: "",
    subtasks: {},
    completedDateErrand: yesterday,
    completedTimeErrand: "10:05",
    seen: true,
    deleted: false,
  },
  {
    id: "982323289987",
    ownerId: "100001",
    assignedId: "100004",
    title: "Pick up kitchen supplies",
    description: "",
    dateErrand: "2024-03-25",
    timeErrand: "10:00",
    completed: true,
    dateNotice: "2024-03-25",
    timeNotice: "09:00",
    repeat: "never",
    marked: true,
    location: "Main Street, Dry Cleaners",
    priority: "medium",
    listId: "",
    subtasks: {},
    completedDateErrand: "2024-03-25",
    completedTimeErrand: "10:05",
    seen: true,
    deleted: false,
  },
  {
    id: "1rewf332441789987",
    ownerId: "100001",
    assignedId: "100001",
    title: "Study for exam",
    description: "",
    dateErrand: twoDaysLater,
    timeErrand: "08:00",
    completed: false,
    dateNotice: twoDaysLater,
    timeNotice: "07:00",
    repeat: "never",
    marked: false,
    location: "Library",
    priority: "high",
    listId: "900f87",
    subtasks: {},
    completedDateErrand: "",
    completedTimeErrand: "",
    seen: true,
    deleted: false,
  },
  {
    id: "123321784353",
    ownerId: "100001",
    assignedId: "100001",
    title: "Buy groceries",
    description: "Buy milk, eggs, bread, and vegetables from the supermarket.",
    dateErrand: yesterday,
    timeErrand: "14:00",
    completed: true,
    dateNotice: yesterday,
    timeNotice: "13:30",
    repeat: "weekendDays",
    marked: false,
    location: "Supermarket",
    priority: "high",
    listId: "12439l",
    subtasks: {},
    completedDateErrand: yesterday,
    completedTimeErrand: "14:17",
    seen: true,
    deleted: false,
  },
  {
    id: "13432fgdtr489987",
    ownerId: "100003",
    assignedId: "100001",
    title: "Submit final project",
    description: "",
    dateErrand: yesterday,
    timeErrand: "09:00",
    completed: false,
    dateNotice: twoDaysAgo,
    timeNotice: "18:00",
    repeat: "monthly",
    marked: false,
    location: "Office",
    priority: "high",
    listId: "",
    subtasks: {},
    completedDateErrand: "",
    completedTimeErrand: "",
    seen: false,
    deleted: false,
  },
  {
    id: "13432489987",
    ownerId: "100001",
    assignedId: "100001",
    title: "Evaluate project report",
    description: "Submit the quarterly project report to the manager.",
    dateErrand: twoDaysAgo,
    timeErrand: "20:00",
    completed: false,
    dateNotice: twoDaysAgo,
    timeNotice: "19:00",
    repeat: "monthly",
    marked: false,
    location: "Office",
    priority: "high",
    listId: "9dsmnb",
    subtasks: {},
    completedDateErrand: "",
    completedTimeErrand: "",
    seen: true,
    deleted: false,
  },
  {
    id: "187656541789987",
    ownerId: "100001",
    assignedId: "100001",
    title: "Call plumber",
    description: "",
    dateErrand: today,
    timeErrand: "19:00",
    completed: false,
    dateNotice: today,
    timeNotice: "18:30",
    repeat: "never",
    marked: false,
    location: "Home",
    priority: "low",
    listId: "900f87",
    subtasks: {},
    completedDateErrand: "",
    completedTimeErrand: "",
    seen: true,
    deleted: false,
  },
  {
    id: "18drewq41723987",
    ownerId: "100001",
    assignedId: "100004",
    title: "Send project report",
    description: "Report of the sections.",
    dateErrand: today,
    timeErrand: "08:00",
    completed: false,
    dateNotice: today,
    timeNotice: "07:30",
    repeat: "never",
    marked: false,
    location: "Home",
    priority: "low",
    listId: "",
    subtasks: {},
    completedDateErrand: "",
    completedTimeErrand: "",
    seen: false,
    deleted: false,
  },
  {
    id: "187656541723987",
    ownerId: "100001",
    assignedId: "100001",
    title: "Send email to CEO",
    description: "Report of the month revenue.",
    dateErrand: today,
    timeErrand: "20:00",
    completed: false,
    dateNotice: today,
    timeNotice: "19:30",
    repeat: "never",
    marked: false,
    location: "Home",
    priority: "low",
    listId: "9dsmnb",
    subtasks: {},
    completedDateErrand: "",
    completedTimeErrand: "",
    seen: true,
    deleted: false,
  },
  {
    id: "123323575487",
    ownerId: "100001",
    assignedId: "100001",
    title: "Attend weekly meeting",
    description: "",
    dateErrand: tomorrow,
    timeErrand: "15:00",
    completed: false,
    dateNotice: tomorrow,
    timeNotice: "10:30",
    repeat: "weekly",
    marked: false,
    location: "Zoom",
    priority: "medium",
    listId: "9dsmnb",
    subtasks: {},
    completedDateErrand: "",
    completedTimeErrand: "",
    seen: false,
    deleted: false,
  },

  {
    id: "1231242fdw987",
    ownerId: "100001",
    assignedId: "100001",
    title: "Invite Alex's family",
    description: "His parents and his siblings.",
    dateErrand: today,
    timeErrand: "16:00",
    completed: false,
    dateNotice: today,
    timeNotice: "15:00",
    repeat: "never",
    marked: true,
    location: "Home",
    priority: "high",
    listId: "900f87",
    subtasks: {},
    completedDateErrand: "",
    completedTimeErrand: "",
    seen: true,
    deleted: false,
  },
  {
    id: "12332fdwsfdw987",
    ownerId: "100001",
    assignedId: "100001",
    title: "Prepare Alex birthday party",
    description: "Plan and organize the birthday party for Alex.",
    dateErrand: twoDaysLater,
    timeErrand: "18:00",
    completed: false,
    dateNotice: tomorrow,
    timeNotice: "10:00",
    repeat: "never",
    marked: false,
    location: "Home",
    priority: "high",
    listId: "900f87",
    subtasks: {},
    completedDateErrand: "",
    completedTimeErrand: "",
    seen: true,
    deleted: false,
  },
  {
    id: "1rewf341789987",
    ownerId: "100001",
    assignedId: "100001",
    title: "Study for test",
    description: "",
    dateErrand: threeDaysLater,
    timeErrand: "08:00",
    completed: false,
    dateNotice: threeDaysLater,
    timeNotice: "20:00",
    repeat: "never",
    marked: false,
    location: "Library",
    priority: "high",
    listId: "9dwe32",
    subtasks: {},
    completedDateErrand: "",
    completedTimeErrand: "",
    seen: true,
    deleted: false,
  },
  {
    id: "152dfwfw789987",
    ownerId: "100001",
    assignedId: "100005",
    title: "Feed the horse",
    description: "",
    dateErrand: threeDaysLater,
    timeErrand: "07:00",
    completed: false,
    dateNotice: threeDaysLater,
    timeNotice: "06:30",
    repeat: "daily",
    marked: true,
    location: "City Park",
    priority: "none",
    listId: "",
    subtasks: {},
    completedDateErrand: "",
    completedTimeErrand: "",
    seen: false,
    deleted: false,
  },
  {
    id: "152dfw56454987",
    ownerId: "100006",
    assignedId: "100001",
    title: "Walk the cat",
    description: "Take the cat for a walk around the park.",
    dateErrand: fourDaysLater,
    timeErrand: "07:00",
    completed: false,
    dateNotice: fourDaysLater,
    timeNotice: "06:30",
    repeat: "daily",
    marked: false,
    location: "City Park",
    priority: "none",
    listId: "",
    subtasks: {},
    completedDateErrand: "",
    completedTimeErrand: "",
    seen: false,
    deleted: false,
  },
  {
    id: "152dfwfw7123189987",
    ownerId: "100003",
    assignedId: "100001",
    title: "Walk the dog",
    description: "Take the dog for a walk around the park.",
    dateErrand: threeDaysAgo,
    timeErrand: "07:00",
    completed: true,
    dateNotice: threeDaysAgo,
    timeNotice: "06:30",
    repeat: "daily",
    marked: true,
    location: "City Park",
    priority: "none",
    listId: "",
    subtasks: {},
    completedDateErrand: threeDaysAgo,
    completedTimeErrand: "07:32",
    seen: true,
    deleted: false,
  },
  {
    id: "152dfw5126454987",
    ownerId: "100006",
    assignedId: "100001",
    title: "Walk the rabbit",
    description: "",
    dateErrand: fourDaysLater,
    timeErrand: "07:00",
    completed: false,
    dateNotice: fourDaysLater,
    timeNotice: "06:30",
    repeat: "daily",
    marked: true,
    location: "City Park",
    priority: "none",
    listId: "",
    subtasks: {},
    completedDateErrand: "",
    completedTimeErrand: "",
    seen: false,
    deleted: false,
  },

  {
    id: "152d3243423987",
    ownerId: "100006",
    assignedId: "100001",
    title: "Walk the rabbit",
    description: "",
    dateErrand: fourDaysLater,
    timeErrand: "07:00",
    completed: false,
    dateNotice: fourDaysLater,
    timeNotice: "06:30",
    repeat: "daily",
    marked: true,
    location: "City Park",
    priority: "none",
    listId: "",
    subtasks: {},
    completedDateErrand: "",
    completedTimeErrand: "",
    seen: false,
    deleted: true,
  },

  {
    id: "152213af454987",
    ownerId: "100001",
    assignedId: "100001",
    title: "Pick up clothes",
    description: "",
    dateErrand: fourDaysLater,
    timeErrand: "07:00",
    completed: false,
    dateNotice: fourDaysLater,
    timeNotice: "06:30",
    repeat: "daily",
    marked: true,
    location: "City Park",
    priority: "none",
    listId: "900f87",
    subtasks: {},
    completedDateErrand: "",
    completedTimeErrand: "",
    seen: false,
    deleted: true,
  },
];

export default errandsData;
