const today = new Date().toISOString().split("T")[0];
const yesterday = new Date(new Date().setDate(new Date().getDate() - 1))
  .toISOString()
  .split("T")[0];
const twoDaysAgo = new Date(new Date().setDate(new Date().getDate() - 2))
  .toISOString()
  .split("T")[0];
const threeDaysAgo = new Date(new Date().setDate(new Date().getDate() - 3))
  .toISOString()
  .split("T")[0];
const tomorrow = new Date(new Date().setDate(new Date().getDate() + 1))
  .toISOString()
  .split("T")[0];
const twoDaysLater = new Date(new Date().setDate(new Date().getDate() + 2))
  .toISOString()
  .split("T")[0];
const threeDaysLater = new Date(new Date().setDate(new Date().getDate() + 3))
  .toISOString()
  .split("T")[0];
const fourDaysLater = new Date(new Date().setDate(new Date().getDate() + 4))
  .toISOString()
  .split("T")[0];

const errandsData = [
  {
    id: "123321789987",
    creatorId: "user123",
    assignedId: "Raul Gonzalez Prieto",
    title: "Pick up dry cleaning",
    description: "Pick up the dry cleaning from the shop on Main Street.",
    dateErrand: yesterday,
    timeErrand: "10:00",
    completed: true,
    dateNotice: yesterday,
    timeNotice: "09:00",
    dateNotice2: yesterday,
    timeNotice2: "09:30",
    repeat: "never",
    marked: true,
    location: "Main Street, Dry Cleaners",
    priority: "medium",
    list: "Personal",
    subtasks: {},
    completedDateErrand: yesterday,
    completedTimeErrand: "10:05",
  },
  {
    id: "1rewf332441789987",
    creatorId: "user123",
    assignedId: "user123",
    title: "Study for exam",
    description: "",
    dateErrand: twoDaysLater,
    timeErrand: "08:00",
    completed: false,
    dateNotice: twoDaysLater,
    timeNotice: "07:00",
    dateNotice2: twoDaysLater,
    timeNotice2: "07:30",
    repeat: "never",
    marked: false,
    location: "Library",
    priority: "high",
    list: "Sin lista",
    subtasks: {},
    completedDateErrand: "",
    completedTimeErrand: "",
  },
  {
    id: "123321784353",
    creatorId: "user123",
    assignedId: "user123",
    title: "Buy groceries",
    description: "Buy milk, eggs, bread, and vegetables from the supermarket.",
    dateErrand: yesterday,
    timeErrand: "14:00",
    completed: true,
    dateNotice: yesterday,
    timeNotice: "13:30",
    dateNotice2: yesterday,
    timeNotice2: "13:45",
    repeat: "weekends",
    marked: false,
    location: "Supermarket",
    priority: "high",
    list: "Supermercado",
    subtasks: {},
    completedDateErrand: yesterday,
    completedTimeErrand: "14:17",
  },
  {
    id: "13432fgdtr489987",
    creatorId: "Carlos Martinez",
    assignedId: "user123",
    title: "Submit final project",
    description: "",
    dateErrand: yesterday,
    timeErrand: "09:00",
    completed: false,
    dateNotice: twoDaysAgo,
    timeNotice: "18:00",
    dateNotice2: twoDaysAgo,
    timeNotice2: "19:00",
    repeat: "everyMonth",
    marked: false,
    location: "Office",
    priority: "high",
    list: "Trabajo",
    subtasks: {},
    completedDateErrand: "",
    completedTimeErrand: "",
  },
  {
    id: "13432489987",
    creatorId: "user123",
    assignedId: "user123",
    title: "Submit project report",
    description: "Submit the quarterly project report to the manager.",
    dateErrand: twoDaysAgo,
    timeErrand: "20:00",
    completed: false,
    dateNotice: twoDaysAgo,
    timeNotice: "19:00",
    dateNotice2: threeDaysAgo,
    timeNotice2: "21:00",
    repeat: "everyMonth",
    marked: false,
    location: "Office",
    priority: "high",
    list: "Trabajo",
    subtasks: {},
    completedDateErrand: "",
    completedTimeErrand: "",
  },
  {
    id: "187656541789987",
    creatorId: "user123",
    assignedId: "user123",
    title: "Call plumber",
    description: "",
    dateErrand: today,
    timeErrand: "19:00",
    completed: false,
    dateNotice: today,
    timeNotice: "18:30",
    dateNotice2: today,
    timeNotice2: "18:45",
    repeat: "never",
    marked: false,
    location: "Home",
    priority: "low",
    list: "Personal",
    subtasks: {},
    completedDateErrand: "",
    completedTimeErrand: "",
  },
  {
    id: "187656541723987",
    creatorId: "user123",
    assignedId: "user123",
    title: "Send email to CEO",
    description: "Report of the month revenue.",
    dateErrand: today,
    timeErrand: "20:00",
    completed: false,
    dateNotice: today,
    timeNotice: "19:30",
    dateNotice2: today,
    timeNotice2: "19:45",
    repeat: "never",
    marked: false,
    location: "Home",
    priority: "low",
    list: "Personal",
    subtasks: {},
    completedDateErrand: "",
    completedTimeErrand: "",
  },
  {
    id: "123323575487",
    creatorId: "user123",
    assignedId: "Antonio Oroz Garcia",
    title: "Attend weekly meeting",
    description: "",
    dateErrand: tomorrow,
    timeErrand: "15:00",
    completed: false,
    dateNotice: tomorrow,
    timeNotice: "10:30",
    dateNotice2: tomorrow,
    timeNotice2: "10:45",
    repeat: "everyWeek",
    marked: false,
    location: "Zoom",
    priority: "medium",
    list: "Trabajo",
    subtasks: {},
    completedDateErrand: "",
    completedTimeErrand: "",
  },
  {
    id: "12332fdwsfdw987",
    creatorId: "user123",
    assignedId: "user123",
    title: "Prepare Alex birthday party",
    description: "Plan and organize the birthday party for Alex.",
    dateErrand: twoDaysLater,
    timeErrand: "18:00",
    completed: false,
    dateNotice: tomorrow,
    timeNotice: "10:00",
    dateNotice2: twoDaysLater,
    timeNotice2: "12:00",
    repeat: "never",
    marked: true,
    location: "Home",
    priority: "high",
    list: "Cumpleaños",
    subtasks: {},
    completedDateErrand: "",
    completedTimeErrand: "",
  },
  {
    id: "1rewf341789987",
    creatorId: "user123",
    assignedId: "user123",
    title: "Study for test",
    description: "",
    dateErrand: threeDaysLater,
    timeErrand: "08:00",
    completed: false,
    dateNotice: threeDaysLater,
    timeNotice: "20:00",
    dateNotice2: threeDaysLater,
    timeNotice2: "07:00",
    repeat: "never",
    marked: false,
    location: "Library",
    priority: "high",
    list: "Universidad",
    subtasks: {},
    completedDateErrand: "",
    completedTimeErrand: "",
  },
  {
    id: "152dfwfw789987",
    creatorId: "user123",
    assignedId: "Esteban Martos",
    title: "Feed the horse",
    description: "",
    dateErrand: threeDaysLater,
    timeErrand: "07:00",
    completed: false,
    dateNotice: threeDaysLater,
    timeNotice: "06:30",
    dateNotice2: threeDaysLater,
    timeNotice2: "06:45",
    repeat: "everyDay",
    marked: true,
    location: "City Park",
    priority: "none",
    list: "Personal",
    subtasks: {},
    completedDateErrand: "",
    completedTimeErrand: "",
  },
  {
    id: "152dfw56454987",
    creatorId: "Jesus Ibañez Perez",
    assignedId: "user123",
    title: "Walk the cat",
    description: "Take the cat for a walk around the park.",
    dateErrand: fourDaysLater,
    timeErrand: "07:00",
    completed: false,
    dateNotice: fourDaysLater,
    timeNotice: "06:30",
    dateNotice2: fourDaysLater,
    timeNotice2: "06:45",
    repeat: "everyDay",
    marked: false,
    location: "City Park",
    priority: "none",
    list: "Personal",
    subtasks: {},
    completedDateErrand: "",
    completedTimeErrand: "",
  },
  {
    id: "152dfwfw7123189987",
    creatorId: "Sergio Lopez Martin",
    assignedId: "user123",
    title: "Walk the dog",
    description: "Take the dog for a walk around the park.",
    dateErrand: threeDaysAgo,
    timeErrand: "07:00",
    completed: true,
    dateNotice: threeDaysAgo,
    timeNotice: "06:30",
    dateNotice2: threeDaysAgo,
    timeNotice2: "06:45",
    repeat: "everyDay",
    marked: true,
    location: "City Park",
    priority: "none",
    list: "Sin lista",
    subtasks: {},
    completedDateErrand: threeDaysAgo,
    completedTimeErrand: "07:32",
  },
  {
    id: "152dfw5126454987",
    creatorId: "Ricardo Macias Prados",
    assignedId: "user123",
    title: "Walk the rabbit",
    description: "",
    dateErrand: fourDaysLater,
    timeErrand: "07:00",
    completed: false,
    dateNotice: fourDaysLater,
    timeNotice: "06:30",
    dateNotice2: fourDaysLater,
    timeNotice2: "06:45",
    repeat: "everyDay",
    marked: true,
    location: "City Park",
    priority: "none",
    list: "Sin lista",
    subtasks: {},
    completedDateErrand: "",
    completedTimeErrand: "",
  },
];

export default errandsData;
