/** @type {import('tailwindcss').Config} */

module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./App.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./constants/**/*.{js,jsx,ts,tsx}",
    "./utils/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  safelist: [
    // Background colors
    "bg-[#F5F5F5]",
    "bg-[#FFFFFF]",
    "bg-[#D3F3E0]",
    "bg-[#F0EEFD]",
    "bg-[#bad6f0]",
    "bg-[#064c8a]",
    "bg-[#e0e0e0]",
    "bg-[#3A3A3A]",
    "bg-[#000000]",
    "bg-[#4A4A4A]",
    "bg-[#121212]",
    "bg-[#1f2120]",
    "bg-[#333333]",
    "bg-[#FDFDFD]",
    "bg-[#254C3B]",
    "bg-[#2F2B45]",
    "bg-[#007AFF]",
    "bg-slate-300",
    "bg-zinc-300",
    "bg-stone-300",
    "bg-red-300",
    "bg-orange-300",
    "bg-amber-300",
    "bg-yellow-300",
    "bg-lime-300",
    "bg-green-300",
    "bg-emerald-300",
    "bg-teal-300",
    "bg-cyan-300",
    "bg-sky-300",
    "bg-blue-300",
    "bg-indigo-300",
    "bg-violet-300",
    "bg-purple-300",
    "bg-fuchsia-300",
    "bg-pink-300",
    "bg-rose-300",
    "bg-gray-300",
    "bg-slate-600",
    "bg-zinc-600",
    "bg-stone-600",
    "bg-red-600",
    "bg-orange-600",
    "bg-amber-600",
    "bg-yellow-600",
    "bg-lime-600",
    "bg-green-600",
    "bg-emerald-600",
    "bg-teal-600",
    "bg-cyan-600",
    "bg-sky-600",
    "bg-blue-600",
    "bg-indigo-600",
    "bg-violet-600",
    "bg-purple-600",
    "bg-fuchsia-600",
    "bg-pink-600",
    "bg-rose-600",
    "bg-gray-600",
    // Text colors
    "text-[#007AFF]",
    "text-[#1E1E1E]",
    "text-[#6E727A]",
    "text-[#A2A6AD]",
    "text-[#161618]",
    "text-[#BFBFBF]",
    "text-[#FDFDFD]",
    "text-[#4B4F55]",
    "text-[#FAFAFA]",
    // Border colors
    "border-[#e0e0e0]",
    "border-[#3A3A3A]",
    "border-[#1E1E1E]",
    "border-[#FDFDFD]",
    "border-[#6E727A]",

    // Shadow colors
    "shadow-[#007AFF]",
  ],
  theme: {
    extend: {
      colors: {
        light: {
          background: "#F5F5F5",
          surfaceBackground: "#FFFFFF",
          iconColor: "#333333",
          blueHeadText: "#007AFF",
          text: "#1E1E1E",
          taskTitle: "#1E1E1E",
          taskSecondText: "#6E727A",
          addNewTaskText: "#A2A6AD",
          outgoingTaskToBg: "#D3F3E0",
          taskIncomingFromBg: "#F0EEFD",
          taskAssignedSharedListBg: "#bad6f0",
          listTitle: "#161618",
          borderColor: "#e0e0e0",
          popupShadow: "#000000",
        },
        dark: {
          background: "#121212",
          surfaceBackground: "#1f2120",
          iconColor: "#FDFDFD",
          blueHeadText: "#007AFF",
          text: "#FDFDFD",
          taskTitle: "#FDFDFD",
          taskSecondText: "#6E727A",
          addNewTaskText: "#4B4F55",
          outgoingTaskToBg: "#254C3B",
          taskIncomingFromBg: "#2F2B45",
          taskAssignedSharedListBg: "#064c8a",
          listTitle: "#FDFDFD",
          borderColor: "#3A3A3A",
          popupShadow: "#4A4A4A",
        },
      },
    },
  },
  plugins: [],
};
